# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "rospy2" = super.buildPythonPackage rec {
    pname = "rospy2";
    version = "1.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/e4/ce21ebcd21fa052847956e07f3861f1aa87f5cac1fb6c352e504d857e7e8/rospy2-1.0.3-py3-none-any.whl";
      sha256 = "0h4zsgzylm6xar2xq0zparqwjz1hwy5qbl8vggm9maf972bfczr4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
